server:
  port: 8081
spring:
  application.name: order-command
  datasource:
    url: jdbc:mysql://localhost:3306/ops?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.format_sql: true
