server:
  port: 8083
spring:
  application.name: order-query
  datasource:
    url: jdbc:mysql://localhost:3306/ops?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: none
